version: '3'
volumes:
    deploy:
        external: false
    nexus-works:
        external: false
services:
    jenkins:
        build: ./jenkins
        volumes:
            - .:/localdev
            - /var/run/docker.sock:/var/run/docker.sock
            - deploy:/usr/share/jenkins/ref/petclinic
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "18080:8080"
        depends_on:
            - dashboard
            - nexus
            - sonar
    nexus:
        image: sonatype/nexus
        volumes:
            - nexus-works:/sonatype-work
        ports:
            - "18081:8081"
    sonar:
        image: sonarqube
        ports:
            - "19000:9000"
    tomcat:
        image: tomcat
        ports:
            - "18888:8080"
        volumes:
            - deploy:/usr/local/tomcat/webapps/
    aem:
        build: /Users/dima/projects/dockeraem
        ports:
            - "14502:4502"
    dashboard:
        build: ./dashboard
        ports:
            - "80:80"
        healthcheck:
            test: curl -f http://dashboard
            interval: 15s
            timeout: 5s
            retries: 3